# pman configuration file
# This is a sample config file. You may need to adjust based on the actual requirements of pman.

# General configuration settings
general:
  project_name: "SoulSymphony"
  version: "1.0.0"
  environment: "production"  # Options might include 'production', 'staging', etc.

# Paths and directories
paths:
  source_directory: "../soul-symphony/"
  output_directory: "output/"
  config_directory: "config/"

# Logging configuration
logging:
  level: "INFO"  # Options might include 'DEBUG', 'INFO', 'WARN', 'ERROR'
  log_file: "log/soul_symphony.log"

